CREATE TABLE IF NOT EXISTS stocks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(20) NOT NULL,
    name varchar(100) NOT NULL,
    market varchar(20),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_stocks_code_active
    ON stocks (code)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_stocks_name ON stocks (name);
CREATE INDEX IF NOT EXISTS idx_stocks_deleted_at ON stocks (deleted_at);
