CREATE TABLE IF NOT EXISTS ticks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_code varchar(20) NOT NULL,
    current_price bigint,
    price_change bigint,
    price_change_rate numeric(10, 2),
    price_change_sign varchar(10),
    trading_volume bigint,
    ticked_at timestamptz,
    collected_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_ticks_stock_code ON ticks (stock_code);
CREATE INDEX IF NOT EXISTS idx_ticks_ticked_at ON ticks (ticked_at);
CREATE INDEX IF NOT EXISTS idx_ticks_stock_code_ticked_at ON ticks (stock_code, ticked_at);
