spring:
  application:
    name: portfolio-service
  grpc:
    server:
      port: ${PORTFOLIO_GRPC_PORT:50055}
  datasource:
    url: ${PORTFOLIO_DB_URL:jdbc:postgresql://localhost:5432/candle_portfolio}
    username: ${PORTFOLIO_DB_USERNAME:candle}
    password: ${PORTFOLIO_DB_PASSWORD:candle}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations: classpath:migration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: ${PORTFOLIO_SERVER_PORT:8085}
