spring:
  application:
    name: notification-service
  grpc:
    server:
      port: ${NOTIFICATION_GRPC_PORT:50057}
  datasource:
    url: ${NOTIFICATION_DB_URL:jdbc:postgresql://localhost:5432/candle?currentSchema=notification,public}
    username: ${NOTIFICATION_DB_USERNAME:candle}
    password: ${NOTIFICATION_DB_PASSWORD:candle}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations: classpath:migration
server:
  port: ${NOTIFICATION_SERVER_PORT:8089}
