/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  engineeringSidebar: [
    {
      type: 'category',
      label: 'Batch',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'batch'}],
    },
    {
      type: 'category',
      label: 'Auth',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'auth'}],
    },
    {
      type: 'category',
      label: 'User',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'user'}],
    },
    {
      type: 'category',
      label: 'Ranking',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'ranking'}],
    },
    {
      type: 'category',
      label: 'Trading',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'trading'}],
    },
    {
      type: 'category',
      label: 'News',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'news'}],
    },
    {
      type: 'category',
      label: 'Notification',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'notification'}],
    },
    {
      type: 'category',
      label: 'Chatting',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'chatting'}],
    },
    {
      type: 'category',
      label: 'Wishlist',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'wishlist'}],
    },
  ],
};

export default sidebars;
