/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  engineeringSidebar: [
    'CONVENTIONS',
    {
      type: 'category',
      label: 'Batch',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'batch'}],
    },
    {
      type: 'category',
      label: 'Ranking',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'ranking'}],
    },
    'TRADING_SERVICE',
  ],
};

export default sidebars;
